import { supabase } from './supabase-client.js';
import { requireAuth } from './auth.js';
import { initNavigation } from './navigation.js';
import { $, clearChildren, formatDate, isOverdue, renderEmpty, setMessage } from './utils.js';
const priorityLabels={very_low:'Sehr unwichtig',low:'Unwichtig',medium:'Mittel',high:'Hoch',very_high:'Sehr hoch'};
function initHedgehogAudio(){ const hedgehogButton=$('#hedgehog-button'); const stopButton=$('#hedgehog-stop-button'); const audio=$('#hedgehog-audio'); if(!audio) return; const showStopButton=()=>{ if(stopButton) stopButton.hidden=false; }; const hideStopButton=()=>{ if(stopButton) stopButton.hidden=true; }; hedgehogButton?.addEventListener('click',()=>{ audio.currentTime=0; audio.play(); }); stopButton?.addEventListener('click',()=>{ audio.pause(); audio.currentTime=0; hideStopButton(); }); audio.addEventListener('play',showStopButton); audio.addEventListener('ended',hideStopButton); }
async function init(){ const session=await requireAuth(); if(!session) return; initNavigation(); try{ const [{data:todos,error:e1},{data:gifts,error:e2},{data:guests,error:e3}]=await Promise.all([supabase.from('todos').select('*'),supabase.from('gift_wishes').select('id'),supabase.from('guest_families').select('*')]); if(e1||e2||e3) throw (e1||e2||e3); const open=todos.filter(t=>!t.is_completed), done=todos.filter(t=>t.is_completed), overdue=open.filter(t=>isOverdue(t.due_date)); $('#stat-open').textContent=open.length; $('#stat-overdue').textContent=overdue.length; $('#stat-done').textContent=done.length; $('#stat-gifts').textContent=gifts.length; $('#stat-families').textContent=guests.length; $('#stat-persons').textContent=guests.reduce((s,g)=>s+1+g.additional_adults+g.children_count,0); const next=open.sort((a,b)=>{ if(!a.due_date&&!b.due_date) return 0; if(!a.due_date) return 1; if(!b.due_date) return -1; return a.due_date.localeCompare(b.due_date); }).slice(0,5); const list=$('#next-todos'); clearChildren(list); if(!next.length) renderEmpty(list,'Alle Aufgaben sind erledigt oder noch nicht angelegt.'); next.forEach(t=>{ const li=document.createElement('li'); li.className='item'; const title=document.createElement('strong'); title.textContent=t.title; const meta=document.createElement('div'); meta.className='actions'; const priority=document.createElement('span'); priority.className=`badge ${t.priority||'medium'}`; priority.textContent=`Priorität: ${priorityLabels[t.priority]||priorityLabels.medium}`; const date=document.createElement('span'); date.className='badge'; date.textContent=formatDate(t.due_date); meta.append(priority,date); li.append(title,meta); list.append(li); }); }catch{ setMessage($('#dashboard-message'),'Die Übersicht konnte nicht geladen werden. Prüfe deine Supabase-Konfiguration.','error'); } }
initHedgehogAudio();
init();
