import { supabase } from './supabase-client.js';
import { requireAuth } from './auth.js';
import { initNavigation } from './navigation.js';
import { $, clearChildren, confirmDialog, normalizeOptional, parseNonNegativeInteger, renderEmpty, setBusy, setMessage } from './utils.js';
let session,rows=[],editing=null; const persons=r=>1+r.additional_adults+r.children_count;
function form(){return $('#guest-form')} async function load(){const {data,error}=await supabase.from('guest_families').select('*').order('family_name'); if(error) throw error; rows=data||[]; render();}
function filtered(){const q=($('#guest-search').value||'').toLowerCase().trim(), sort=$('#guest-sort').value; let arr=rows.filter(r=>!q||r.family_name.toLowerCase().includes(q)||r.main_guest_name.toLowerCase().includes(q)); return arr.sort((a,b)=>sort==='persons'?persons(b)-persons(a):a.family_name.localeCompare(b.family_name,'de'));}
function totals(){const adults=rows.reduce((s,r)=>s+1+r.additional_adults,0), kids=rows.reduce((s,r)=>s+r.children_count,0); $('#total-adults').textContent=adults; $('#total-children').textContent=kids; $('#total-persons').textContent=adults+kids;}
function render(){totals(); const body=$('#guest-table-body'); clearChildren(body); const arr=filtered(); if(!arr.length){renderEmpty($('#guest-empty'),'Keine passenden Gästegruppen gefunden.'); return;} clearChildren($('#guest-empty')); arr.forEach(r=>{const tr=document.createElement('tr'); [r.family_name,r.main_guest_name,String(r.additional_adults),String(r.children_count),String(persons(r)),r.note||''].forEach(v=>{const td=document.createElement('td'); td.textContent=v; tr.append(td);}); const td=document.createElement('td'); const wrap=document.createElement('div'); wrap.className='actions'; const edit=document.createElement('button'); edit.className='button button-secondary'; edit.textContent='Bearbeiten'; edit.addEventListener('click',()=>startEdit(r)); const del=document.createElement('button'); del.className='button button-danger'; del.textContent='Löschen'; del.addEventListener('click',()=>remove(r.id)); wrap.append(edit,del); td.append(wrap); tr.append(td); body.append(tr);});}
function reset(){editing=null; form().reset(); $('#guest-adults').value='0'; $('#guest-children').value='0'; $('#guest-submit').textContent='Gästegruppe speichern'; form().classList.remove('edit-mode');}
function startEdit(r){editing=r.id; $('#family-name').value=r.family_name; $('#main-guest').value=r.main_guest_name; $('#guest-adults').value=r.additional_adults; $('#guest-children').value=r.children_count; $('#guest-note').value=r.note||''; $('#guest-submit').textContent='Änderungen speichern'; form().classList.add('edit-mode'); form().scrollIntoView({behavior:'smooth',block:'center'});}
async function remove(id){if(!await confirmDialog('Diese Gästegruppe wirklich löschen?')) return; const {error}=await supabase.from('guest_families').delete().eq('id',id); if(error) return setMessage($('#guest-message'),'Der Eintrag konnte nicht gelöscht werden.','error'); rows=rows.filter(r=>r.id!==id); setMessage($('#guest-message'),'Gästegruppe wurde gelöscht.'); render();}
async function init(){session=await requireAuth(); if(!session) return; initNavigation(); $('#guest-search').addEventListener('input',render); $('#guest-sort').addEventListener('change',render); $('#guest-cancel').addEventListener('click',reset); form().addEventListener('submit',async e=>{e.preventDefault(); const family=$('#family-name').value.trim(), main=$('#main-guest').value.trim(), adults=parseNonNegativeInteger($('#guest-adults').value), children=parseNonNegativeInteger($('#guest-children').value); if(!family||!main) return setMessage($('#guest-message'),'Familienname und Hauptgast sind erforderlich.','error'); if(adults===null||children===null) return setMessage($('#guest-message'),'Erwachsene und Kinder müssen ganze Zahlen ab 0 sein.','error'); const btn=$('#guest-submit'); setBusy(btn,true,'Speichern …'); try{const payload={family_name:family,main_guest_name:main,additional_adults:adults,children_count:children,note:normalizeOptional($('#guest-note').value),user_id:session.user.id}; const q=editing?supabase.from('guest_families').update(payload).eq('id',editing).select().single():supabase.from('guest_families').insert(payload).select().single(); const {data,error}=await q; if(error) throw error; rows=editing?rows.map(r=>r.id===editing?data:r):[...rows,data]; reset(); setMessage($('#guest-message'),'Gästegruppe wurde gespeichert.'); render();}catch{setMessage($('#guest-message'),'Die Gästegruppe konnte nicht gespeichert werden.','error');}finally{setBusy(btn,false);}}); try{await load();}catch{setMessage($('#guest-message'),'Gästeliste konnte nicht geladen werden.','error');}}
init();
