import { supabase } from './supabase-client.js';
import { requireAuth } from './auth.js';
import { initNavigation } from './navigation.js';
import { $, clearChildren, confirmDialog, isValidHttpUrl, normalizeOptional, parseOptionalPrice, renderEmpty, setBusy, setMessage } from './utils.js';
let session,wishes=[],editing=null; const labels={low:'Niedrig',medium:'Mittel',high:'Hoch'};
function form(){return $('#gift-form')} async function load(){const {data,error}=await supabase.from('gift_wishes').select('*').order('created_at',{ascending:false}); if(error) throw error; wishes=data||[]; render();}
function render(){const list=$('#gift-list'); clearChildren(list); if(!wishes.length) return renderEmpty(list,'Noch keine Geschenkwünsche eingetragen.'); wishes.forEach(w=>{const card=document.createElement('article'); card.className='card'; const h=document.createElement('h3'); h.textContent=w.title; const p=document.createElement('p'); p.className='muted'; p.textContent=w.description||'Keine Beschreibung hinterlegt.'; const meta=document.createElement('div'); meta.className='actions'; const pr=document.createElement('span'); pr.className=`badge ${w.priority||''}`; pr.textContent=w.priority?`Priorität: ${labels[w.priority]}`:'Ohne Priorität'; meta.append(pr); if(w.price!==null){const price=document.createElement('span'); price.className='badge'; price.textContent=`${Number(w.price).toLocaleString('de-DE',{style:'currency',currency:'EUR'})}`; meta.append(price);} const actions=document.createElement('div'); actions.className='actions'; if(w.url){const a=document.createElement('a'); a.className='button button-secondary'; a.href=w.url; a.target='_blank'; a.rel='noopener noreferrer'; a.textContent='Link öffnen'; actions.append(a);} const edit=document.createElement('button'); edit.className='button button-secondary'; edit.textContent='Bearbeiten'; edit.addEventListener('click',()=>startEdit(w)); const del=document.createElement('button'); del.className='button button-danger'; del.textContent='Löschen'; del.addEventListener('click',()=>remove(w.id)); actions.append(edit,del); card.append(h,p,meta,actions); list.append(card);});}
function reset(){editing=null; form().reset(); $('#gift-submit').textContent='Wunsch speichern'; form().classList.remove('edit-mode');}
function startEdit(w){editing=w.id; $('#gift-title').value=w.title; $('#gift-description').value=w.description||''; $('#gift-url').value=w.url||''; $('#gift-price').value=w.price??''; $('#gift-priority').value=w.priority||''; $('#gift-submit').textContent='Änderungen speichern'; form().classList.add('edit-mode'); form().scrollIntoView({behavior:'smooth',block:'center'});}
async function remove(id){if(!await confirmDialog('Diesen Geschenkwunsch wirklich löschen?')) return; const {error}=await supabase.from('gift_wishes').delete().eq('id',id); if(error) return setMessage($('#gift-message'),'Der Wunsch konnte nicht gelöscht werden.','error'); wishes=wishes.filter(w=>w.id!==id); setMessage($('#gift-message'),'Wunsch wurde gelöscht.'); render();}
async function init(){session=await requireAuth(); if(!session) return; initNavigation(); $('#gift-cancel').addEventListener('click',reset); form().addEventListener('submit',async e=>{e.preventDefault(); const btn=$('#gift-submit'), title=$('#gift-title').value.trim(), url=normalizeOptional($('#gift-url').value), price=parseOptionalPrice($('#gift-price').value); if(!title) return setMessage($('#gift-message'),'Bitte gib eine Bezeichnung ein.','error'); if(!isValidHttpUrl(url)) return setMessage($('#gift-message'),'Bitte gib einen gültigen Link mit http:// oder https:// ein.','error'); if(price===null && $('#gift-price').value!=='') return setMessage($('#gift-message'),'Der Preis darf nicht negativ sein.','error'); setBusy(btn,true,'Speichern …'); try{const payload={title,description:normalizeOptional($('#gift-description').value),url,price,priority:normalizeOptional($('#gift-priority').value),user_id:session.user.id}; const q=editing?supabase.from('gift_wishes').update(payload).eq('id',editing).select().single():supabase.from('gift_wishes').insert(payload).select().single(); const {data,error}=await q; if(error) throw error; wishes=editing?wishes.map(w=>w.id===editing?data:w):[data,...wishes]; reset(); setMessage($('#gift-message'),'Geschenkwunsch wurde gespeichert.'); render();}catch{setMessage($('#gift-message'),'Der Geschenkwunsch konnte nicht gespeichert werden.','error');}finally{setBusy(btn,false);}}); try{await load();}catch{setMessage($('#gift-message'),'Geschenkwünsche konnten nicht geladen werden.','error');}}
init();
