import { supabase } from './supabase-client.js';
import { requireAuth } from './auth.js';
import { initNavigation } from './navigation.js';
import { $, clearChildren, confirmDialog, normalizeOptional, parseNonNegativeInteger, renderEmpty, setBusy, setMessage } from './utils.js';
let session, schedules=[], tables=[], guests=[], editingSchedule=null, editingTable=null;
const statusLabels={planned:'Geplant',confirmed:'Bestätigt',open:'Offen',done:'Erledigt'};
const persons=g=>1+g.additional_adults+g.children_count;
async function load(){ const [s,t,g]=await Promise.all([supabase.from('wedding_day_schedule').select('*').order('starts_at'),supabase.from('seating_tables').select('*').order('name'),supabase.from('guest_families').select('*').order('family_name')]); if(s.error||t.error||g.error) throw (s.error||t.error||g.error); schedules=s.data||[]; tables=t.data||[]; guests=g.data||[]; renderSchedules(); renderTables(); }
function renderSchedules(){ const body=$('#schedule-body'); clearChildren(body); if(!schedules.length){ renderEmpty($('#schedule-empty'),'Noch keine Programmpunkte angelegt.'); return; } clearChildren($('#schedule-empty')); schedules.forEach(item=>{ const tr=document.createElement('tr'); [item.starts_at,item.title,item.location||'',item.responsible_person||'',item.note||'',statusLabels[item.status]||item.status].forEach(v=>{ const td=document.createElement('td'); td.textContent=v; tr.append(td); }); const td=document.createElement('td'); const actions=document.createElement('div'); actions.className='actions'; const edit=document.createElement('button'); edit.className='button button-secondary'; edit.textContent='Bearbeiten'; edit.addEventListener('click',()=>startScheduleEdit(item)); const del=document.createElement('button'); del.className='button button-danger'; del.textContent='Löschen'; del.addEventListener('click',()=>removeSchedule(item.id)); actions.append(edit,del); td.append(actions); tr.append(td); body.append(tr); }); }
function guestsAtTable(id){ return guests.filter(g=>g.table_id===id); }
function renderTables(){ const body=$('#table-body'); clearChildren(body); if(!tables.length){ renderEmpty($('#table-empty'),'Noch keine Tische angelegt. Gäste können danach in der Gästeliste zugeordnet werden.'); return; } clearChildren($('#table-empty')); tables.forEach(table=>{ const assigned=guestsAtTable(table.id), occupied=assigned.reduce((sum,g)=>sum+persons(g),0), free=table.size-occupied, conflict=free<0; const tr=document.createElement('tr'); if(conflict) tr.className='row-danger'; const values=[table.name,String(table.size),assigned.map(g=>`${g.family_name} (${persons(g)})`).join(', ')||'Keine Gäste',String(occupied),String(Math.max(free,0)),conflict?`Überbelegt um ${Math.abs(free)} Plätze`:'OK']; values.forEach(v=>{ const td=document.createElement('td'); td.textContent=v; tr.append(td); }); const td=document.createElement('td'); const actions=document.createElement('div'); actions.className='actions'; const edit=document.createElement('button'); edit.className='button button-secondary'; edit.textContent='Bearbeiten'; edit.addEventListener('click',()=>startTableEdit(table)); const del=document.createElement('button'); del.className='button button-danger'; del.textContent='Löschen'; del.addEventListener('click',()=>removeTable(table.id)); actions.append(edit,del); td.append(actions); tr.append(td); body.append(tr); }); }
function resetSchedule(){ editingSchedule=null; $('#schedule-form').reset(); $('#schedule-status').value='planned'; $('#schedule-submit').textContent='Programmpunkt speichern'; $('#schedule-form').classList.remove('edit-mode'); }
function resetTable(){ editingTable=null; $('#table-form').reset(); $('#table-size').value='8'; $('#table-submit').textContent='Tisch speichern'; $('#table-form').classList.remove('edit-mode'); }
function startScheduleEdit(item){ editingSchedule=item.id; $('#schedule-time').value=item.starts_at; $('#schedule-title').value=item.title; $('#schedule-location').value=item.location||''; $('#schedule-owner').value=item.responsible_person||''; $('#schedule-note').value=item.note||''; $('#schedule-status').value=item.status||'planned'; $('#schedule-submit').textContent='Änderungen speichern'; $('#schedule-form').classList.add('edit-mode'); $('#schedule-form').scrollIntoView({behavior:'smooth',block:'center'}); }
function startTableEdit(table){ editingTable=table.id; $('#table-name').value=table.name; $('#table-size').value=table.size; $('#table-note').value=table.note||''; $('#table-submit').textContent='Änderungen speichern'; $('#table-form').classList.add('edit-mode'); $('#table-form').scrollIntoView({behavior:'smooth',block:'center'}); }
async function removeSchedule(id){ if(!await confirmDialog('Diesen Programmpunkt wirklich löschen?')) return; const {error}=await supabase.from('wedding_day_schedule').delete().eq('id',id); if(error) return setMessage($('#planning-message'),'Programmpunkt konnte nicht gelöscht werden.','error'); schedules=schedules.filter(s=>s.id!==id); renderSchedules(); setMessage($('#planning-message'),'Programmpunkt wurde gelöscht.'); }
async function removeTable(id){ if(!await confirmDialog('Diesen Tisch wirklich löschen? Zugeordnete Gäste werden vom Tisch entfernt.')) return; const {error}=await supabase.from('seating_tables').delete().eq('id',id); if(error) return setMessage($('#planning-message'),'Tisch konnte nicht gelöscht werden.','error'); tables=tables.filter(t=>t.id!==id); guests=guests.map(g=>g.table_id===id?{...g,table_id:null}:g); renderTables(); setMessage($('#planning-message'),'Tisch wurde gelöscht.'); }
async function init(){ session=await requireAuth(); if(!session) return; initNavigation(); $('#schedule-cancel').addEventListener('click',resetSchedule); $('#table-cancel').addEventListener('click',resetTable); $('#schedule-form').addEventListener('submit',async e=>{ e.preventDefault(); const title=$('#schedule-title').value.trim(); if(!title) return setMessage($('#planning-message'),'Bitte gib einen Programmpunkt ein.','error'); const btn=$('#schedule-submit'); setBusy(btn,true,'Speichern …'); try{ const payload={starts_at:$('#schedule-time').value,title,location:normalizeOptional($('#schedule-location').value),responsible_person:normalizeOptional($('#schedule-owner').value),note:normalizeOptional($('#schedule-note').value),status:$('#schedule-status').value,user_id:session.user.id}; const q=editingSchedule?supabase.from('wedding_day_schedule').update(payload).eq('id',editingSchedule).select().single():supabase.from('wedding_day_schedule').insert(payload).select().single(); const {data,error}=await q; if(error) throw error; schedules=editingSchedule?schedules.map(s=>s.id===editingSchedule?data:s):[...schedules,data]; schedules.sort((a,b)=>a.starts_at.localeCompare(b.starts_at)); resetSchedule(); renderSchedules(); setMessage($('#planning-message'),'Programmpunkt wurde gespeichert.'); }catch{ setMessage($('#planning-message'),'Programmpunkt konnte nicht gespeichert werden.','error'); }finally{ setBusy(btn,false); } }); $('#table-form').addEventListener('submit',async e=>{ e.preventDefault(); const name=$('#table-name').value.trim(), size=parseNonNegativeInteger($('#table-size').value); if(!name||!size) return setMessage($('#planning-message'),'Tischname und eine Tischgröße ab 1 sind erforderlich.','error'); const btn=$('#table-submit'); setBusy(btn,true,'Speichern …'); try{ const payload={name,size,note:normalizeOptional($('#table-note').value),user_id:session.user.id}; const q=editingTable?supabase.from('seating_tables').update(payload).eq('id',editingTable).select().single():supabase.from('seating_tables').insert(payload).select().single(); const {data,error}=await q; if(error) throw error; tables=editingTable?tables.map(t=>t.id===editingTable?data:t):[...tables,data]; resetTable(); renderTables(); setMessage($('#planning-message'),'Tisch wurde gespeichert.'); }catch{ setMessage($('#planning-message'),'Tisch konnte nicht gespeichert werden.','error'); }finally{ setBusy(btn,false); } }); try{ await load(); }catch{ setMessage($('#planning-message'),'Planung konnte nicht geladen werden. Prüfe, ob das Datenbankschema aktualisiert wurde.','error'); } }
init();
