import { supabase } from './supabase-client.js';
import { requireAuth } from './auth.js';
import { initNavigation } from './navigation.js';
import { $, clearChildren, confirmDialog, isValidHttpUrl, normalizeOptional, renderEmpty, setBusy, setMessage } from './utils.js';

let session, entries = [], editing = null;
const defaults = [
  ['Standesamt Konstanz','Historisches Rathaus Konstanz','https://www.konstanz.de/start/leben%2Bin%2Bkonstanz/heiraten%2Bin%2Bkonstanz.html','25 Gäste-Sitzplätze','werktags reguläre Gebühren; Samstag 220 €'],
  ['Standesamt Konstanz','Schloss Mainau – Roter Saal','https://www.mainau.de/de/angebote/heiraten','bis 25 Personen','Samstag Standesamt 257 €, zusätzlich Raummiete der Mainau nach Angebot'],
  ['Standesamt Konstanz','Schloss Mainau – Weißer Saal','https://www.mainau.de/de/angebote/heiraten','bis 100 Personen','Samstag Standesamt 257 €, zusätzlich Raummiete der Mainau nach Angebot'],
  ['Standesamt Konstanz','Rosgartenmuseum – Zunftsaal','https://www.rosgartenmuseum.de/heiraten-im-rosgartenmuseum/','nicht veröffentlicht','auf Anfrage'],
  ['Standesamt Reichenau','Trauzimmer im Rathaus Reichenau','https://www.reichenau.de/de/Rathaus-Service/Buergerservice/Heiraten-auf-der-Reichenau','nicht veröffentlicht','nicht veröffentlicht'],
  ['Standesamt Allensbach','Kleiner Sitzungssaal im Rathaus','https://allensbach.traukalender-online.de/de/Kleiner-Sitzungssaal-51.html','nicht eindeutig veröffentlicht','reguläre Standesamtsgebühren'],
  ['Standesamt Allensbach','Großer Sitzungssaal im Rathaus','https://allensbach.traukalender-online.de/de/Grosser-Sitzungssaal-52.html','nicht eindeutig veröffentlicht','reguläre Standesamtsgebühren'],
  ['Standesamt Allensbach','Gemeindesteg Allensbach','https://allensbach.traukalender-online.de/de/Gemeindesteg-55.html','max. 15 Personen','180 € zusätzlich'],
  ['Standesamt Allensbach','Höhenberg','https://allensbach.traukalender-online.de/de/Hoehrenberg-54.html','nicht fest ausgewiesen; keine Bestuhlung','180 € zusätzlich'],
  ['Standesamt Allensbach','Torkel','https://allensbach.traukalender-online.de/de/Torkel-53.html','nicht eindeutig veröffentlicht','laut Detailseite 180 € zusätzlich'],
  ['Standesamt Allensbach','Rathaus Kaltbrunn','https://allensbach.traukalender-online.de/de/Rathaus-Kaltbrunn-59.html','max. 15 Gäste','180 € zusätzlich'],
  ['Standesamt Allensbach','Schloss Freudental','https://allensbach.traukalender-online.de/de/Schloss-Freudental-57.html','bis 80 Gäste','150 € Standesamts-Aufpreis, zusätzliche Schlosskosten möglich'],
  ['Standesamt Allensbach','Schloss Langenrain','https://allensbach.traukalender-online.de/de/Schloss-Langenrain-58.html','10–160 Personen','150 € Standesamts-Aufpreis, zusätzliche Schlosskosten möglich'],
  ['Standesamt Meersburg','Historischer Rathaussaal','https://www.meersburg.de/de/Leben-Rathaus/Rathaus/Buergerservice/Dienstleistungen-A-Z/Dienstleistung?id=1621&view=publish','bis 30 Personen','reguläre Gebühren; Termin-Vormerkung 50 €'],
  ['Standesamt Meersburg','Burg Meersburg – Kapellenturm','https://www.burg-meersburg.de/wp-content/uploads/2025/03/Standesamt_Kapellenturm.pdf','bis 60 Personen','480 € bis 30 Personen, danach 15 € je weitere Person; zusätzlich 60 € Standesamts-Aufpreis'],
  ['Standesamt Meersburg','Burg Meersburg – Renaissance-Saal','https://www.burg-meersburg.de/wp-content/uploads/2025/03/Standesamt_Renaissance-Saal.pdf','bis 150 Personen','konkreter Mietpreis auf Anfrage; zusätzlich 60 € Standesamts-Aufpreis'],
  ['Standesamt Meersburg','Neues Schloss – Raum Schönborn','https://www.neues-schloss-meersburg.de/tagen-feiern/privatkunden/heiraten-im-neuen-schloss-meersburg/','je nach Bestuhlung etwa 45–72 Personen','Raummiete auf Anfrage; zusätzlich 60 € Standesamts-Aufpreis'],
  ['Standesamt Meersburg','Neues Schloss – Spiegelsaal','https://www.neues-schloss-meersburg.de/tagen-feiern/privatkunden/heiraten-im-neuen-schloss-meersburg/','nicht aktuell als feste Trau-Kapazität veröffentlicht','Raummiete auf Anfrage; zusätzlich 60 € Standesamts-Aufpreis'],
  ['Standesamt Meersburg','Neues Schloss – Teehäuschen','https://www.neues-schloss-meersburg.de/tagen-feiern/privatkunden/heiraten-im-neuen-schloss-meersburg/','etwa 18–30 Personen, je nach Aufbau','Raummiete auf Anfrage; zusätzlich 60 € Standesamts-Aufpreis']
];
function payloadFrom(values){ const [office_name, room_name, website_url, capacity, price] = values; return { office_name, room_name, website_url, capacity, price, rating: 5, user_id: session.user.id }; }
async function seedDefaults(){ const { data, error } = await supabase.from('registry_office_rooms').insert(defaults.map(payloadFrom)).select(); if(error) throw error; entries = data || []; }
async function load(){ const { data, error } = await supabase.from('registry_office_rooms').select('*').order('office_name').order('room_name'); if(error) throw error; entries = data || []; if(!entries.length) await seedDefaults(); render(); }
function ratingText(rating){ return `${rating}/10`; }
function render(){ const body = $('#registry-body'); clearChildren(body); if(!entries.length){ renderEmpty($('#registry-empty'), 'Noch keine Standesämter eingetragen.'); return; } clearChildren($('#registry-empty')); entries.forEach(entry => { const tr = document.createElement('tr'); [entry.office_name, entry.room_name].forEach(value => { const td = document.createElement('td'); td.textContent = value; tr.append(td); }); const linkTd = document.createElement('td'); if(entry.website_url){ const a = document.createElement('a'); a.href = entry.website_url; a.target = '_blank'; a.rel = 'noopener noreferrer'; a.textContent = 'Webseite öffnen'; linkTd.append(a); } tr.append(linkTd); [entry.capacity, entry.price, ratingText(entry.rating)].forEach(value => { const td = document.createElement('td'); td.textContent = value; tr.append(td); }); const td = document.createElement('td'); const actions = document.createElement('div'); actions.className = 'actions'; const edit = document.createElement('button'); edit.className = 'button button-secondary'; edit.textContent = 'Bearbeiten'; edit.addEventListener('click', () => startEdit(entry)); const del = document.createElement('button'); del.className = 'button button-danger'; del.textContent = 'Löschen'; del.addEventListener('click', () => remove(entry.id)); actions.append(edit, del); td.append(actions); tr.append(td); body.append(tr); }); }
function syncRatingLabel(){ $('#registry-rating-output').textContent = $('#registry-rating').value; }
function reset(){ editing = null; $('#registry-form').reset(); $('#registry-rating').value = '5'; syncRatingLabel(); $('#registry-submit').textContent = 'Eintrag speichern'; $('#registry-form').classList.remove('edit-mode'); }
function startEdit(entry){ editing = entry.id; $('#registry-office').value = entry.office_name; $('#registry-room').value = entry.room_name; $('#registry-url').value = entry.website_url || ''; $('#registry-capacity').value = entry.capacity; $('#registry-price').value = entry.price; $('#registry-rating').value = entry.rating; syncRatingLabel(); $('#registry-submit').textContent = 'Änderungen speichern'; $('#registry-form').classList.add('edit-mode'); $('#registry-form').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
async function remove(id){ if(!await confirmDialog('Diesen Standesamt-Eintrag wirklich löschen?')) return; const { error } = await supabase.from('registry_office_rooms').delete().eq('id', id); if(error) return setMessage($('#registry-message'), 'Der Eintrag konnte nicht gelöscht werden.', 'error'); entries = entries.filter(entry => entry.id !== id); render(); setMessage($('#registry-message'), 'Eintrag wurde gelöscht.'); }
async function init(){ session = await requireAuth(); if(!session) return; initNavigation(); $('#registry-rating').addEventListener('input', syncRatingLabel); $('#registry-cancel').addEventListener('click', reset); $('#registry-form').addEventListener('submit', async event => { event.preventDefault(); const office_name = $('#registry-office').value.trim(), room_name = $('#registry-room').value.trim(), website_url = normalizeOptional($('#registry-url').value), capacity = $('#registry-capacity').value.trim(), price = $('#registry-price').value.trim(), rating = Number($('#registry-rating').value); if(!office_name || !room_name || !capacity || !price) return setMessage($('#registry-message'), 'Bitte fülle Standesamt, Raum, Kapazität und Preis aus.', 'error'); if(!isValidHttpUrl(website_url)) return setMessage($('#registry-message'), 'Bitte gib einen gültigen Link mit http:// oder https:// ein.', 'error'); const btn = $('#registry-submit'); setBusy(btn, true, 'Speichern …'); try{ const payload = { office_name, room_name, website_url, capacity, price, rating, user_id: session.user.id }; const query = editing ? supabase.from('registry_office_rooms').update(payload).eq('id', editing).select().single() : supabase.from('registry_office_rooms').insert(payload).select().single(); const { data, error } = await query; if(error) throw error; entries = editing ? entries.map(entry => entry.id === editing ? data : entry) : [...entries, data]; entries.sort((a, b) => a.office_name.localeCompare(b.office_name) || a.room_name.localeCompare(b.room_name)); reset(); render(); setMessage($('#registry-message'), 'Eintrag wurde gespeichert.'); }catch{ setMessage($('#registry-message'), 'Der Eintrag konnte nicht gespeichert werden. Prüfe, ob das Datenbankschema aktualisiert wurde.', 'error'); }finally{ setBusy(btn, false); } }); try{ await load(); }catch{ setMessage($('#registry-message'), 'Standesämter konnten nicht geladen werden. Prüfe, ob das Datenbankschema aktualisiert wurde.', 'error'); } }
init();
